- name: openrouter/google/gemini-2.5-pro-preview-03-25
  edit_format: diff-fenced
  weak_model_name: openrouter/google/gemini-2.0-flash-001
  editor_model_name: openrouter/anthropic/claude-3.7-sonnet
  use_repo_map: true
